sudo: required
services:
  - docker

before_install:
  - docker build -t nestor94/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true nestor94/react-test npm test

after_success:
  - docker build -t nestor94/multi-client ./client
  - docker build -t nestor94/multi-nginx ./nginx
  - docker build -t nestor94/multi-server ./server
  - docker build -t nestor94/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push them into Docker Hub
  - docker push nestor94/multi-client
  - docker push nestor94/multi-nginx
  - docker push nestor94/multi-server
  - docker push nestor94/multi-worker

